<footer class="flex flex-col justify-end md:justify-between mt-20  mx-10 items-center pb-2  md:items-end md:mx-16 md:flex-row flex-grow">
        <p class="text-light items-center opacity-50 md:items-start">Copyright © 2022 PESTANA CR7 LIFESTYLE HOTELS.</p>
        <div class="flex justify-between space-x-14">
            <span class="text-light opacity-50 cursor-pointer">
                Facebook
            </span>
            <span class="text-light opacity-50 cursor-pointer">
                instgram
            </span>
            <span class="text-light opacity-50 cursor-pointer">
                twitter
            </span>
        </div>
</footer>
<script src="/assets/script/main.js"></script>
</body>
</html>