<footer class="flex flex-col justify-end md:justify-between mt-20  mx-10 items-center pb-2  md:items-end md:mx-16 md:flex-row flex-grow">
        <p class="text-light items-center opacity-50 md:items-start">Copyright © 2022 PESTANA CR7 LIFESTYLE HOTELS.</p>
        <div class="flex justify-between space-x-14">
            <span class="text-light opacity-50 cursor-pointer">
                Facebook
            </span>
            <span class="text-light opacity-50 cursor-pointer">
                instgram
            </span>
            <span class="text-light opacity-50 cursor-pointer">
                twitter
            </span>
        </div>
</footer>
<script>

function roomTypeSelect() {
  let selectionContainer = document.getElementById('selection-container');
    let selectButton = document.getElementById('room-select');
    let selectedRoomValue = document.getElementById('selected-room-value');
    let selectedRoomView = document.getElementById('selected-room-view');
    let roomTypesContainer = document.getElementById('room-types-container');
    let roomTypes = roomTypesContainer.firstElementChild.children;
    //  Suit Types
    let suit = `<div class="flex justify-center flex-col" id="suit-div">
                    <button id="suit-select" type="button" class="relative flex justify-between items-center bg-slate-400 border focus:outline-none shdow text-slate-50 rounded focus:ring ring-slate-900 w-48 ">
                        
                        <?php if(isset($this->viewData['chamber'])) { ?>
                            <input type="text" name="suit-type" id="selected-suit-value" class="hidden" value="<?php echo $this->viewData['chamber']->suitType;?>">
                        <p id="selected-suit-view" class="px-4 cursor-pointer"><?php echo $this->viewData['chamber']->suitType;?></p> <?php } else{ ?>
                            <input type="text" name="suit-type" id="selected-suit-value" class="hidden">
                            <p id="selected-suit-view" class="px-4 cursor-pointer">Select suit type</p>
                        <?php } ?>
                        <span class="border-l p-2">
                            <svg  class="w-5 h-5"
                            fill="#1e293b" height="200px" width="200px" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 330.002 330.002" xml:space="preserve" transform="rotate(180)" stroke="#1e293b"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_iconCarrier"> <path id="XMLID_105_" d="M324.001,209.25L173.997,96.75c-5.334-4-12.667-4-18,0L6.001,209.25c-6.627,4.971-7.971,14.373-3,21 c2.947,3.93,7.451,6.001,12.012,6.001c3.131,0,6.29-0.978,8.988-3.001L164.998,127.5l141.003,105.75c6.629,4.972,16.03,3.627,21-3 C331.972,223.623,330.628,214.221,324.001,209.25z"></path> </g>
                            </svg>
                        </span>
                        <div id="suit-list" class="absolute hidden  top-full min-w-full w-max bg-secondary shadow-md mt-1 rounded">
                            <ul id="suit-types" class="text-left border rounded">
                                <li class="px-4 py-1 hover:bg-slate-900 border-b rounded cursor-pointer">Standard</li>
                                <li class="px-4 py-1 hover:bg-slate-900 border-b rounded cursor-pointer">Junior</li>
                                <li class="px-4 py-1 hover:bg-slate-900 border-b rounded cursor-pointer">Presidential</li>
                                <li class="px-4 py-1 hover:bg-slate-900 border-b rounded cursor-pointer">Penthouse</li>
                                <li class="px-4 py-1 hover:bg-slate-900 border-b rounded cursor-pointer">Honeymoon</li>
                                <li class="px-4 py-1 hover:bg-slate-900 border-b rounded cursor-pointer">Bridal</li>
                            </ul>
                        </div>
                    </button>
                </div>`;
    let suitContainer = document.createElement('div');
    let suitCapacityContainer = document.getElementById('suit-capacity-conatiner');
    if(selectedRoomValue.value == "Suit" && document.getElementById('suit-select') == null ) {
          suitContainer.innerHTML = suit;
          selectionContainer.append(suitContainer);
          suitCapacityContainer.classList.replace('hidden', 'flex');
          suitSelect();
      }
    selectButton.addEventListener('click', () => {
      roomTypesContainer.classList.toggle('hidden');
  });
  for(let i = 0; i < roomTypes.length; i++) {
      roomTypes[i].addEventListener('click', (event) => {
      for(let i = 0; i < roomTypes.length; i++) {
          roomTypes[i].classList.remove('hidden');
      }
      let choice = event.target;
      choice.classList.add('hidden');
      let roomType = choice.innerText;
      selectedRoomView.innerHTML = roomType;
      selectedRoomValue.value = selectedRoomView.innerHTML;
      if(selectedRoomValue.value == "Suit" && document.getElementById('suit-select') == null ) {
          suitContainer.innerHTML = suit;
          selectionContainer.append(suitContainer);
          suitCapacityContainer.classList.replace('hidden', 'flex');
          suitSelect();
      }else {
          suitContainer.remove();
          suitCapacityContainer.classList.replace('flex', 'hidden');
      }
  });
  }
}
function suitSelect() {
  let suitSelectButton = document.getElementById('suit-select');
  let selectedSuitValue = document.getElementById('selected-suit-value');
  let selectedSuitView = document.getElementById('selected-suit-view');
  let suitTypesContainer = document.getElementById('suit-list');
  let suitTypes = suitTypesContainer.firstElementChild.children;
  let suitCapacity = document.getElementById('suit-capacity');
  suitSelectButton.addEventListener('click', () => {
      suitTypesContainer.classList.toggle('hidden');
  });
  for(let i = 0; i < suitTypes.length; i++) {
      suitTypes[i].addEventListener('click', (e) => {
        selectedSuitView.innerHTML = e.target.innerText;
        selectedSuitValue.value = selectedSuitView.innerHTML;
      });
  }
  suitCapacity.addEventListener('change', () => {
      if(suitCapacity.value < 1 || isNaN(suitCapacity.value)) {
          suitCapacity.value = 1;
      }
      else if(suitCapacity.value > 6 ) {
          suitCapacity.value = 6;
      }
  });
  
}
</script>
<script src="/assets/script/main.js"></script>
</body>
</html>