<?php include VIEW . "components/header.phtml";?>
    <!--hero section-->
    <section id="hero" class="mx-10 mt-20 md:mx-16">
        <!--flex container-->
        <div class="container flex flex-col-reverse md:flex-row  space-y-0 items-center md:space-y-0 ">
            <!--left item-->
            <div class="flex flex-col space-y-12 md:w-1/2">
                <h1 class="max-w-md text-4xl font-bold text-center md:text-5xl md:text-left text-slate-50">
                    Book your best Suit & rooms
                </h1>
                <p class="max-w-md text-light  text-center md:text-left opacity-70">
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis tempore, maiores magnam praesentium optio laboriosam distinctio consectetur necessitatibus sed. Nostrum, natus suscipit sed sint nobis consequuntur, exercitationem ullam itaque corporis doloremque maxime?
                </p>
                <div class="flex justify-center items-center md:justify-start">
                    <a class="bg-secondary text-light  font-medium px-6 py-2 rounded-full  hover:bg-dark hover:border border-light" href="">Book now</a>
                </div>
            </div>
            <!--right item-->
            <div class="w-1/2">
                <img src="/assets/images/hero-image.jpg" alt="">
            </div>
        </div>
    </section>
<?php include VIEW . "components/footer.phtml";?>