<?php include VIEW . "components/header.phtml"; ?>
<form action="http://hotel.com/page/Login/error" method="POST" id="login-form" class="flex w-max md:px-14 md:h-80 h-76 px-8 absolute bg-light  flex-col items-center rounded 
drop-shadow-2xl justify-center gap-3 top-1/4 left-1/3">
        <h2 class="text-dark font-bold text-xl">Login</h2>
        <p class="text-dark opacity-70">login to your account and start booking</p>
        <?php echo isset($this->viewData['message']) ? $this->viewData['message'] : ''; ?>
    <div class="flex flex-col justify-between gap-y-3">
        <input
         class="h-10 text-center rounded border-2 border-secondary focus:border-dark text-dark"
         type="text" name="user_name" placeholder="Enter your user name">
        <input
         class="h-10 text-center rounded border-2 border-secondary focus:border-dark text-dark"
         type="password" name="password" placeholder="Enter your password">
    </div>
    <div class="flex items-center justify-center w-1/3 bg-secondary rounded text-light ">
        <input
        class="h-10 cursor-pointer"
         type="submit" value="Login" name="login">
    </div>
    <a class="opacity-80 cursor-pointer text-dark">Sign-up</a>
</form>
<?php include VIEW . "components/footer.phtml"; ?>
